-- CreateTable
CREATE TABLE "Admin" (
    "ID" SERIAL NOT NULL,
    "CODE" TEXT DEFAULT '',
    "NAME" TEXT DEFAULT '',
    "EMAIL" TEXT,
    "PHONE" TEXT DEFAULT '',
    "ROLE" TEXT DEFAULT '',
    "PASSWORD" TEXT DEFAULT '',
    "CREATED_AT" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Admin_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "Customer" (
    "ID" SERIAL NOT NULL,
    "CODE" TEXT NOT NULL DEFAULT '',
    "NAME" TEXT NOT NULL DEFAULT '',
    "SSM_REGISTRATION_NO" TEXT DEFAULT '',
    "TAX_IDENTIFICATION_NO" TEXT DEFAULT '',
    "SST_NO" TEXT DEFAULT '',
    "MSIC_CODE" TEXT DEFAULT '',
    "BUSINESS_NATURE" TEXT DEFAULT '',
    "PIC_NAME" TEXT DEFAULT '',
    "EMAIL" TEXT,
    "PHONE_NO" TEXT DEFAULT '',
    "ADDRESS" TEXT DEFAULT '',
    "CREDIT_TERM" TEXT NOT NULL DEFAULT '',
    "ADMIN_ID" INTEGER NOT NULL DEFAULT 0,
    "CREDIT_LIMIT" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "CREATED_AT" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Customer_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "Product" (
    "ID" SERIAL NOT NULL,
    "CODE" TEXT NOT NULL DEFAULT '',
    "NAME" TEXT NOT NULL DEFAULT '',
    "CATEGORY" TEXT NOT NULL DEFAULT '',
    "BASE_UOM" TEXT NOT NULL DEFAULT '',
    "STOCK" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "UNIT_PRICE" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "Transaction" (
    "ID" SERIAL NOT NULL,
    "DOC_NUM" TEXT NOT NULL DEFAULT '',
    "TRANSACTION_DATE" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CUSTOMER_ID" INTEGER NOT NULL DEFAULT 0,
    "ADMIN_ID" INTEGER NOT NULL DEFAULT 0,
    "TOTAL_PRICE" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "REF_DOC_NO" TEXT DEFAULT '',
    "DELIVERY_DATE" TIMESTAMP(3),
    "SHIPPING_METHOD" TEXT DEFAULT '',
    "COMISSION" DOUBLE PRECISION DEFAULT 0,
    "REMARK" TEXT DEFAULT '',
    "STATUS" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "Transaction_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "Transaction_Detail" (
    "ID" SERIAL NOT NULL,
    "TRANSACTION_ID" INTEGER NOT NULL,
    "PRODUCT_ID" INTEGER NOT NULL,
    "QTY" INTEGER NOT NULL,
    "UNIT_PRICE" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "Transaction_Detail_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "Admin_EMAIL_key" ON "Admin"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "Customer_EMAIL_key" ON "Customer"("EMAIL");

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_CUSTOMER_ID_fkey" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "Customer"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_ADMIN_ID_fkey" FOREIGN KEY ("ADMIN_ID") REFERENCES "Admin"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction_Detail" ADD CONSTRAINT "Transaction_Detail_TRANSACTION_ID_fkey" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "Transaction"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction_Detail" ADD CONSTRAINT "Transaction_Detail_PRODUCT_ID_fkey" FOREIGN KEY ("PRODUCT_ID") REFERENCES "Product"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
